const $=id=>document.getElementById(id)
const storageKey='sudoku-web-v1'
let game,selected=-1,noteMode=false,history=[]
function validSave(s){return s&&[0,1,2].includes(s.difficulty)&&Number.isInteger(s.seconds)&&s.seconds>=0&&Number.isInteger(s.mistakes)&&s.mistakes>=0&&['puzzle','board','solution'].every(k=>Array.isArray(s[k])&&s[k].length===81&&s[k].every(v=>Number.isInteger(v)&&v>=0&&v<=9))&&s.solution.every(v=>v>0)&&s.puzzle.every((v,i)=>!v||(v===s.solution[i]&&s.board[i]===v))&&Array.isArray(s.notes)&&s.notes.length===81&&s.notes.every(n=>Array.isArray(n)&&n.every(v=>Number.isInteger(v)&&v>=1&&v<=9))}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(game))}catch(_){$('saved').textContent='浏览器无法保存进度，本局仍可继续游玩'}}
function timeLabel(){return `${String(Math.floor(game.seconds/60)).padStart(2,'0')}:${String(game.seconds%60).padStart(2,'0')}`}
function newGame(difficulty){const {puzzle,solution}=Sudoku.generate(difficulty);game={puzzle,solution,board:puzzle.slice(),notes:Array.from({length:81},()=>[]),difficulty,seconds:0,mistakes:0,completed:false};selected=-1;noteMode=false;history=[];render();save()}
function snapshot(){history.push({board:game.board.slice(),notes:game.notes.map(n=>n.slice())})}
function change(){game.completed=game.board.every((v,i)=>v===game.solution[i]);render();save()}
function enter(value){if(selected<0||game.puzzle[selected]||game.completed||(noteMode&&game.board[selected]))return;snapshot();if(noteMode){const notes=game.notes[selected];game.notes[selected]=notes.includes(value)?notes.filter(n=>n!==value):notes.concat(value).sort()}else{game.board[selected]=value;game.notes[selected]=[];if(value!==game.solution[selected])game.mistakes++}change()}
function erase(){if(selected<0||game.puzzle[selected]||game.completed)return;snapshot();game.board[selected]=0;game.notes[selected]=[];change()}
function render(){const row=Math.floor(selected/9),col=selected%9;document.querySelectorAll('.cell').forEach((cell,i)=>{const r=Math.floor(i/9),c=i%9,v=game.board[i];const related=selected>=0&&(r===row||c===col||(Math.floor(r/3)===Math.floor(row/3)&&Math.floor(c/3)===Math.floor(col/3)));cell.className=['cell',game.puzzle[i]?'fixed':'',related?'related':'',selected>=0&&v&&v===game.board[selected]?'same':'',selected===i?'selected':'',v&&v!==game.solution[i]?'error':'',c===2||c===5?'box-right':'',r===2||r===5?'box-bottom':''].join(' ');cell.replaceChildren();if(v)cell.textContent=v;else{const grid=document.createElement('span');grid.className='note-grid';for(let n=1;n<=9;n++){const note=document.createElement('span');note.textContent=game.notes[i].includes(n)?n:'';grid.append(note)}cell.append(grid)}cell.setAttribute('aria-label',`第${r+1}行第${c+1}列，${v||'空格'}${game.puzzle[i]?'，题目数字':''}${v&&v!==game.solution[i]?'，错误':''}`);cell.setAttribute('aria-pressed',String(selected===i));cell.tabIndex=i===(selected<0?0:selected)?0:-1});$('difficulty').value=String(game.difficulty);$('timer').textContent=timeLabel();$('stats').textContent=`错误 ${game.mistakes} · 空格 ${game.board.filter(v=>!v).length}`;$('status').textContent=game.completed?`恭喜完成！用时 ${timeLabel()}`:'静下心来，每一步都有答案';$('notes').classList.toggle('active',noteMode);$('notes').setAttribute('aria-pressed',String(noteMode));$('notes').querySelector('small').textContent=`笔记：${noteMode?'开':'关'}`;$('undo').disabled=!history.length||game.completed;for(const id of ['erase','hint','notes'])$(id).disabled=game.completed;document.querySelectorAll('#keyboard button').forEach(b=>b.disabled=game.completed)}
for(let i=0;i<81;i++){const cell=document.createElement('button');cell.type='button';cell.className='cell';cell.addEventListener('click',()=>{selected=i;render()});$('board').append(cell)}
for(let n=1;n<=9;n++){const button=document.createElement('button');button.type='button';button.textContent=n;button.addEventListener('click',()=>enter(n));$('keyboard').append(button)}
$('new').addEventListener('click',()=>{if(confirm('开始新游戏？当前进度将被替换。'))newGame(game.difficulty)})
$('difficulty').addEventListener('change',()=>{const next=Number($('difficulty').value);if(confirm('切换难度并开始新游戏？'))newGame(next);else $('difficulty').value=String(game.difficulty)})
$('notes').addEventListener('click',()=>{noteMode=!noteMode;render()})
$('erase').addEventListener('click',erase)
$('undo').addEventListener('click',()=>{if(!history.length||game.completed)return;const last=history.pop();game.board=last.board;game.notes=last.notes;change()})
$('hint').addEventListener('click',()=>{if(game.completed)return;let i=selected;if(i<0||game.puzzle[i]||game.board[i]===game.solution[i])i=game.board.findIndex((v,j)=>v!==game.solution[j]);if(i<0)return;snapshot();selected=i;game.board[i]=game.solution[i];game.notes[i]=[];change()})
document.addEventListener('keydown',e=>{if(e.target.closest('select,input,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;if(/^[1-9]$/.test(e.key)){e.preventDefault();enter(Number(e.key))}else if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();erase()}else if(e.key.toLowerCase()==='n'&&!game.completed){noteMode=!noteMode;render()}else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(selected<0)selected=0;else{const r=Math.floor(selected/9),c=selected%9;selected=e.key==='ArrowUp'?Math.max(0,r-1)*9+c:e.key==='ArrowDown'?Math.min(8,r+1)*9+c:e.key==='ArrowLeft'?r*9+Math.max(0,c-1):r*9+Math.min(8,c+1)}render();$('board').children[selected].focus()}})
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(validSave(saved)){game=saved;game.completed=game.board.every((v,i)=>v===game.solution[i])}}catch(_){}
if(game)render();else newGame(0)
setInterval(()=>{if(!document.hidden&&!game.completed){game.seconds++;$('timer').textContent=timeLabel();save()}},1000)
document.addEventListener('visibilitychange',save)
window.addEventListener('pagehide',save)
